$(document).ready(function() {
    $("#nav_link_1").click(function(){
        $("#tab_1").css("display","block");
        $("#tab_2").css("display","none");
        $("#tab_3").css("display","none");
        $(".nav_link_1").addClass("active");
        $(".nav_link_2").removeClass("active");
        $(".nav_link_3").removeClass("active");
        $(".tab_tips").removeClass("tab_img_3");
        $(".tab_1_content").css("width","876px")
    })
    $("#nav_link_2").click(function(){
        $("#tab_2").css("display","block");
        $("#tab_1").css("display","none");
        $("#tab_3").css("display","none");
        $(".nav_link_2").addClass("active");
        $(".nav_link_1").removeClass("active");
        $(".nav_link_3").removeClass("active");
        $(".tab_tips").removeClass("tab_img_3");
        $(".tab_1_content").css("width","1140px")
    })
    $("#nav_link_3").click(function(){
        $("#tab_3").css("display","block");
        $("#tab_2").css("display","none");
        $("#tab_1").css("display","none");
        $(".nav_link_3").addClass("active");
        $(".nav_link_2").removeClass("active");
        $(".nav_link_1").removeClass("active");
        $(".tab_tips").addClass("tab_img_3");
        $(".tab_1_content").css("width","977px")
    })
})
